code_journal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('code_journals.urls'))
]

code_journals/urls.py
from django.urls import path

from . import views
app_name = 'code_journals'
urlpatterns = [
    #Home page
    path('', views.index, name = "index"),

    #Show all topics.
    path('topics/<int:topic_id>', views.topics, name='topics'),
]

code_journals/models.py
from django.db import models
# Create your models here.

class Topic(models.Model):
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
   
        
    def __str__(self):
        return str(self.text)

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        return str(self.text[:50]+"...")

code_journals/views.py
from django.shortcuts import render
from . models import Topic
# Create your views here.
def index(request):
    return render(request, 'code_journals/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'code_journals/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = { 'topic':topic, 'entries': entries}
    return render(request, 'code_journals/topic.html', context)
    

code_journals/templates/code_journals/base.html
<p>
    <a href="{% url 'code_journals:index' %}">Code Jorunal</a>
    <a href="{% url 'code_journals:topics' %}">Topics</a> 
</p>
{% block content %}{% endblock content %}

code_journals/templates/code_journals/index.html
{% extends "code_journals/base.html" %}

{% block content %}

<p>Code Journal will help you keep track of your 
    python in CIS 240 for the coding topics you learn.</p>
{% endblock content %}

code_journals/templates/code_journals/topic.html
{% extends 'code_journals/base.html' %}
{% block content %}

<p>Topic: {{topic}}</p>

<p>Entries:</p>
<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>
            There are not entries for this topic yet.
        </li>
{% endfor %}
</ul>

{% endblock content %}

code_journals/templates/code_journals/topics.html
{% extends "code_journals/base.html" %}

{% block content %}

<p>Topics</p>

<ul>
    {% for topic in topics %}
        <li>{{ topic }}</li>
            <a href="{% url 'code_journals:topic' topic.id %}">{{ topic }}</a>
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}